# Generated by Django 5.0.7 on 2024-07-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
