# Generated by Django 5.0.7 on 2024-07-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_spots',
            field=models.ManyToManyField(related_name='created_by', to='spot.spot'),
        ),
        migrations.AddField(
            model_name='user',
            name='participated_spots',
            field=models.ManyToManyField(related_name='participants', to='spot.spot'),
        ),
    ]
