# Generated by Django 5.0.7 on 2024-07-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spot', '0001_initial'),
        ('user', '0002_user_created_spots_user_participated_spots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
