# Generated by Django 5.0.7 on 2024-07-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
        ('user', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('icon', models.IntegerField(blank=True, default=0, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_spots', models.ManyToManyField(related_name='created_by', to='spot.spot')),
                ('friends', models.ManyToManyField(related_name='my_friends', to='user.member')),
                ('participated_spots', models.ManyToManyField(related_name='participants', to='spot.spot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
