# Generated by Django 5.0.7 on 2024-07-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_member_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
